import React, { useState } from 'react';
import { AuditRecord } from '../types';
import { FileText, Printer, Check } from 'lucide-react';

interface ReportProps {
  data: AuditRecord[];
}

const Report: React.FC<ReportProps> = ({ data }) => {
  const [auditorNotes, setAuditorNotes] = useState(
    "Based on the analytical procedures performed, we identified high-risk accounts requiring specific allowance under PSAK 71. The overall portfolio health indicates..."
  );

  const totalExposure = data.reduce((sum, r) => sum + r.totalBalance, 0);
  const impairedCount = data.filter(r => r.status === 'Impaired').length;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="p-8 h-full overflow-y-auto">
      <div className="max-w-4xl mx-auto bg-white text-slate-900 p-12 rounded-lg shadow-2xl printable-area">
        
        <div className="border-b-2 border-slate-800 pb-6 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-4xl font-extrabold text-slate-900">AUDIT REPORT</h1>
            <p className="text-slate-500 mt-2 font-mono text-sm uppercase">Generated by Auditor-AI Pro</p>
          </div>
          <div className="text-right">
            <p className="font-bold">Date: {new Date().toLocaleDateString()}</p>
            <p className="text-sm text-slate-500">Ref: AUD-{new Date().getFullYear()}-001</p>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-bold border-b border-slate-300 mb-4 pb-1">1. Executive Summary</h3>
          <p className="text-sm text-slate-600 mb-2 italic">Auditor's Note (Editable):</p>
          <textarea
            value={auditorNotes}
            onChange={(e) => setAuditorNotes(e.target.value)}
            className="w-full p-4 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 focus:ring-2 focus:ring-primary-500 focus:outline-none"
            rows={4}
          />
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-bold border-b border-slate-300 mb-4 pb-1">2. Key Statistics</h3>
          <div className="grid grid-cols-2 gap-8">
            <div className="bg-slate-50 p-4 rounded-lg">
              <span className="block text-slate-500 text-sm">Total Exposure</span>
              <span className="block text-2xl font-bold">${totalExposure.toLocaleString()}</span>
            </div>
            <div className="bg-slate-50 p-4 rounded-lg">
              <span className="block text-slate-500 text-sm">Records Analyzed</span>
              <span className="block text-2xl font-bold">{data.length}</span>
            </div>
            <div className="bg-slate-50 p-4 rounded-lg">
              <span className="block text-slate-500 text-sm">Impaired Accounts (>90 Days)</span>
              <span className="block text-2xl font-bold text-red-600">{impairedCount}</span>
            </div>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-bold border-b border-slate-300 mb-4 pb-1">3. Methodology</h3>
          <p className="text-slate-700 leading-relaxed text-sm">
            This audit was conducted using the Auditor-AI Pro system. Data was tested for existence, valuation, and completeness. 
            Credit loss estimation follows the simplified approach allowed under PSAK 71 for trade receivables.
          </p>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-200 flex justify-between items-center text-sm text-slate-400">
          <p>Confidential Document</p>
          <p>Page 1 of 1</p>
        </div>

      </div>

      <div className="fixed bottom-8 right-8 print:hidden">
        <button 
          onClick={handlePrint}
          className="flex items-center space-x-2 bg-primary-600 hover:bg-primary-500 text-white px-6 py-3 rounded-full shadow-lg transition-transform hover:-translate-y-1"
        >
          <Printer size={20} />
          <span className="font-bold">Print / Save as PDF</span>
        </button>
      </div>

      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .printable-area, .printable-area * {
            visibility: visible;
          }
          .printable-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            margin: 0;
            padding: 20px;
            box-shadow: none;
          }
          .print\\:hidden {
            display: none;
          }
        }
      `}</style>
    </div>
  );
};

export default Report;